services:
    web:
      build: .
      command: sh -c "python manage.py migrate && gunicorn VulnTrackAdmin.wsgi:application --bind 0.0.0.0:8000"
      volumes:
        - .:/app
      ports:
        - "8000:8000"
      env_file:
        - .env

    redis:
      image: redis:7-alpine


    celery_worker:
      build: .
      command: celery -A VulnTrackAdmin worker --loglevel=info
      volumes:
        - .:/app
      env_file:
        - .env
      depends_on:
        - redis