[mypy]
python_version = 3.13
ignore_missing_imports = True
disallow_untyped_defs = False

[mypy-*.models]
ignore_errors = True

[mypy-django.*]
ignore_errors = True

[mypy-rest_framework.*]
ignore_errors = True
